apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-argo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/daminma/argocd.git
    targetRevision: HEAD
    path: . 
  destination:
    server: https://kubernetes.default.svc
    namespace: my-argocd
  syncPolicy:
    syncOptions:
    - CreateNameSpace=true
    automated:
      selfHeal: true
      prune: true

